title: 50 years of Werner Report
subheading: A history of Europe
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  All the digital contents behind the werner report.
baseurl: "/werner-report" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: c2dh
github_username:  c2dh
excerpt_separator: <!-- more -->
# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
default_lang: en
languages:
  - en
  - fr
collections:
  authors:
    output: true
    permalink: /a/:slug/
permalink: "/:year/:month/:day/:title:output_ext"
